name: Python Scraper CI

on:
  push:
    branches: [Tim]
  pull_request:
    branches: [Tim]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install system dependencies
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable

    - name: Install Python Dependencies
      working-directory: ./Scraper
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest coverage webdriver-manager

    - name: Run Scraper Tests
      working-directory: ./Scraper
      run: |
        pytest tests/ --cov=Scraper --cov-report=term-missing -v