name: Python Scraper CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y msedge

    - name: Install Python Dependencies
      working-directory: ./Scraper
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest coverage webdriver-manager

    - name: Run Scraper Tests
      working-directory: ./Scraper
      run: |
        pytest tests/ --cov=Scraper --cov-report=term-missing -v
